site_name: Japanese Language
site_url: https://mydomain.org/DocsByKaran
nav: 
 - Home: index.md
 

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        dark: Switch to light mode
      primary: teal
      accent: lime
 # Add this line to specify the custom template directory

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/karan0207
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/karan0207s
    

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true

plugins:
  - search

